Update resource validation procedure.
opensearch-project/OpenSearch-Dashboards pull request #1019
Opened 2021-12-12 15:43 UTC by Arbuzov

New validation procedure allows to embed base64 encoded images

Signed-off-by: Serge Arbuzov <info@whitediver.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[#989]
 
### Check List
- [+] New functionality includes testing.
  - [] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [+] Commits are signed per the DCO using --signoff

2021-12-13 21:08 UTC, tmarkley reviewed
Thank you for contributing! This is a great enhancement to custom branding.

I think it would be worthwhile to add some more details to the .yml file about the valid values now that they can be something other than URLs:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9037b61e9d4da3c44f0ba0fab8f803db5873ef89/config/opensearch_dashboards.yml#L152-L163

Also, can you make the PR title and commit message more specific? "Update resource validation procedure" sells these changes a little short.

Finally, can you add a comment to https://github.com/opensearch-project/documentation-website/issues/241 describing the additional functionality that you're adding here so that we can capture that in the documentation?

2021-12-13 21:11 UTC, tmarkley commented on src/core/server/rendering/rendering_service.test.ts
> +  describe('isResourceValid()', () => {
Can you add functional tests to accompany the [existing custom branding functional tests](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/5edf03062d40a92385070f53904b2344c0ffd351/test/functional/apps/visualize/_custom_branding.js#L55)?

2021-12-14 08:40 UTC, kavilla commented
Could you update as well: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/rendering/__mocks__/rendering_service.ts.

Without it, I wasn't able to run unit tests. Just to make sure if you could run through the pull request checklist that would be good to ensure verification is there.

Thank you!

2021-12-14 08:40 UTC, kavilla requested changes
Unit tests.

2021-12-14 14:51 UTC, tmarkley commented
I just realized that this PR was targeting `1.2`. This has to be `main` since we need to merge there first. Please rebase.

2021-12-16 09:29 UTC, kavilla commented
> I just realized that this PR was targeting `1.2`. This has to be `main` since we need to merge there first. Please rebase and resolve conflicts.

Another way could be to cherry pick your commit onto `main` and do a force push I believe.

2021-12-16 18:42 UTC, tmarkley commented
> > I just realized that this PR was targeting `1.2`. This has to be `main` since we need to merge there first. Please rebase and resolve conflicts.
> 
> Another way could be to cherry pick your commit onto `main` and do a force push I believe.

Yep that works too! Probably easier.

2022-01-05 16:58 UTC, tmarkley commented
Hi @Arbuzov, are you able to address the comments above?

2022-02-18 09:17 UTC, kavilla commented
Hi @Arbuzov, any updates on the above?

Any thing we can do to help? Thanks!

2022-03-27 22:57 UTC, Arbuzov commented
Sorry, new year holydays, then all off this things...
I will manage that this week.

2022-06-21 23:20 UTC, kavilla commented
Closing. Please feel free to re-open when ready!

2022-06-21 23:20 UTC, closed without merging