[BUG] Add Data table bucket Split rows agg limit of 3
opensearch-project/OpenSearch-Dashboards pull request #1179
Opened 2022-01-25 14:03 UTC by RoyiSitbon

Signed-off-by: sitbubu <royi.sitbon@logz.io>

### Description
The default limit of 3 “Split rows” aggregated buckets isn't applied on this visualization which allows adding more buckets and can harm cluster performance.

In other types of visualizations, there is a default limit of up to 3 “Split rows” aggregated buckets, e.g. Horizontal-Bar visualizations.

We wish to have an option to configure the max,min limitation for the “Split rows” aggregated bucket under dataTable vis.
i.e. Using this configuration, we will limit the max amount to 3:
<img width="979" alt="Screen Shot 2022-02-03 at 14 25 02" src="https://user-images.githubusercontent.com/12782945/152342371-570f7721-5139-43c4-a90c-a01693afa0a9.png">

This way we will see the next result in our UI:
<img width="517" alt="splitRowsLimited" src="https://user-images.githubusercontent.com/12782945/152342546-5c5f18eb-eaea-49b8-b8d9-8c2b03a4db33.png">

If we won't set any limitation, i.e:
<img width="282" alt="Screen Shot 2022-02-03 at 14 27 12" src="https://user-images.githubusercontent.com/12782945/152342691-60dd46b6-b746-4bac-bde8-4288987d3bc1.png">

We will have same behavior as now:
<img width="526" alt="splitRowsUnlimited" src="https://user-images.githubusercontent.com/12782945/152342749-0d8215fb-7bae-4997-bc61-3c8ba5a3b469.png">

**linked issue:**
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1178

2022-01-26 06:22 UTC, kavilla commented
Hello @RoyiSitbon,

Thanks for opening this. Will check it out, right now it's blocked because the tests are failing due to this [issue](https://github.com/opensearch-project/opensearch-build/issues/1497).

Initial nitpick feedback would be if you can some of the content you added to the PR to the commit description that provide insight on the commit without having to come to the PR. Also, I believe this could potential to add a quick test to verify it limits to 3.

2022-01-26 06:46 UTC, RoyiSitbon commented
> Hello @RoyiSitbon,
> 
> Thanks for opening this. Will check it out, right now it's blocked because the tests are failing due to this [issue](https://github.com/opensearch-project/opensearch-build/issues/1497).
> 
> Initial nitpick feedback would be if you can some of the content you added to the PR to the commit description that provide insight on the commit without having to come to the PR. Also, I believe this could potential to add a quick test to verify it limits to 3.

Hey, sure. Thanks for the feedback.

2022-01-28 11:51 UTC, jgough commented
I often want to split on more than 3 fields and losing this ability would be a step backwards when data sets are small and performance is not an issue.  Is there any scope of making this configurable setting with a default of 3?

2022-01-28 11:58 UTC, jgough commented
The functionality of allowing more than 3 splits in data tables has been present since Kibana 4 and I use this ability regularly.  Sadly I have many visualisations that would break and just not be possible unless it were possible to configure this limit.

2022-01-29 07:59 UTC, kavilla commented
> The functionality of allowing more than 3 splits in data tables has been present since Kibana 4 and I use this ability regularly. Sadly I have many visualisations that would break and just not be possible unless it were possible to configure this limit.

> I often want to split on more than 3 fields and losing this ability would be a step backwards when data sets are small and performance is not an issue. Is there any scope of making this configurable setting with a default of 3?

I see there is probably historical reason to have this not be capped at 3. 

Perhaps, @ahopp or @kgcreative, what do y'all think about this change? Does it seems like a good improvement to make all of them similar in behavior and have an override config? Or can we gather more insight on the potential impact?

2022-01-31 20:36 UTC, kgcreative commented
@kavilla, @RoyiSitbon, @jgough - I would prefer to handle this in a way where we don't introduce a breaking change. I would suggest a configuration option that's empty by default to introduce a split row limit (either in stack management, or kibana yml, or somewhere else). This would allow admins to configure this limit if needed for performance reasons, but wouldn't break existing functionality.

This setting should then be enforced by any visualization that uses split rows in agg buckets.

maybe something like `aggBucketSplitRowLimit: num;`, where `null` allows for any number of split rows.

For additional corner case handling, existing visualizations with split rows beyond N would only display N split rows.

2022-02-01 09:59 UTC, RoyiSitbon commented
> @kavilla, @RoyiSitbon, @jgough - I would prefer to handle this in a way where we don't introduce a breaking change. I would suggest a configuration option that's empty by default to introduce a split field limit (either in stack management, or kibana yml, or somewhere else). This would allow admins to configure this limit if needed for performance reasons, but wouldn't break existing functionality.
> 
> This setting should then be enforced by any visualization that uses split fields in agg buckets.
> 
> maybe something like `aggBucketSplitFieldLimit: num;`, where `null` or `0` allows for any number of split fields.
> 
> For additional corner case handling, existing visualizations with split fields beyond N would only display N split rows.

Sure, that sounds good to me.
I'll work on a configurable solution if agreed by all.
@kavilla @jgough 

Thanks

2022-02-03 12:47 UTC, RoyiSitbon commented
Hey, I changed it to be a configurable solution as talked.
Thanks

2022-02-15 05:38 UTC, kavilla commented
Hi @RoyiSitbon, if you rebase the tests should pass (granted if no failures by new implementation). Would you like for me to rebase for you on your branch? Let me know. Thank you!

2022-02-15 18:31 UTC, RoyiSitbon commented
> Hi @RoyiSitbon, if you rebase the tests should pass (granted if no failures by new implementation). Would you like for me to rebase for you on your branch? Let me know. Thank you!
> 
> Also, would there be an ability to add some tests to test this new functionality.

Hey, rebased
Also, I will try to think of a tailored test. Thank you

2022-02-20 13:22 UTC, RoyiSitbon commented
> Hi @RoyiSitbon, if you rebase the tests should pass (granted if no failures by new implementation). Would you like for me to rebase for you on your branch? Let me know. Thank you!
> 
> Also, would there be an ability to add some tests to test this new functionality.

Added a new functional test with the right flow as well.

2022-03-03 19:33 UTC, ananzh commented
Sorry. I commented on the wrong place: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1178#issuecomment-1050569191

I will re-check it.

2022-03-04 21:19 UTC, ananzh commented
Hey @RoyiSitbon 

After the latest change, advanced settings does not set a default split limit which is great. I have verified that. But I think the function is still not working right? For example, I set the advanced settings with/without max to limit the split to 3:

<img width="908" alt="Screen Shot 2022-03-04 at 1 09 17 PM" src="https://user-images.githubusercontent.com/79961084/156841918-2f2ca87e-72b2-48d2-bda5-ca8516349712.png">


Then go to visualization, create a data table using eCommerce sample data. However, I could still split even I have 3 buckets. First, the "Split rows" option has no changes and still clickable.
<img width="1607" alt="Screen Shot 2022-03-04 at 1 13 09 PM" src="https://user-images.githubusercontent.com/79961084/156842465-a11993b9-d350-4d0b-8a89-8de3f26cf76c.png">

Second, adding one more split is still working. We could see a descending based on product quality.
<img width="1606" alt="Screen Shot 2022-03-04 at 1 12 14 PM" src="https://user-images.githubusercontent.com/79961084/156842207-55552488-e48e-46f1-bb96-9c5187eba772.png">

So I am bit confused here. Did I mis-use or mis-understand here? pls help

2022-03-05 05:07 UTC, ananzh commented
> Hey @RoyiSitbon
> 
> After the latest change, advanced settings does not set a default split limit which is great. I have verified that. But I think the function is still not working right? For example, I set the advanced settings with/without max to limit the split to 3:
> 
> <img alt="Screen Shot 2022-03-04 at 1 09 17 PM" width="908" src="https://user-images.githubusercontent.com/79961084/156841918-2f2ca87e-72b2-48d2-bda5-ca8516349712.png">
> 
> Then go to visualization, create a data table using eCommerce sample data. However, I could still split even I have 3 buckets. First, the "Split rows" option has no changes and still clickable. <img alt="Screen Shot 2022-03-04 at 1 13 09 PM" width="1607" src="https://user-images.githubusercontent.com/79961084/156842465-a11993b9-d350-4d0b-8a89-8de3f26cf76c.png">
> 
> Second, adding one more split is still working. We could see a descending based on product quality. <img alt="Screen Shot 2022-03-04 at 1 12 14 PM" width="1606" src="https://user-images.githubusercontent.com/79961084/156842207-55552488-e48e-46f1-bb96-9c5187eba772.png">
> 
> So I am bit confused here. Did I mis-use or mis-understand here? pls help

My bad. It turns a cache issue and need to refresh the page to reload the settings. It is better to use `requiresPageReload: true` to improve user experience.

2022-03-05 05:12 UTC, ananzh commented
Meanwhile, I have several questions
1) do other graph typess besides data table also have this issue? or do they have some bucket split default limit in the code? 
2) if other graph types have the same issue, do we or can we support them?
3) if no other graph types have the same issue and data table is the only type, do we need to use `{"table": {"bucket":{}}}`?

Probably we should discuss more here.

2022-03-06 06:41 UTC, RoyiSitbon commented
> requiresPageReload

Hey,
unlike this dynamic configuration setting, other agg types have constant settings at the moment.
The reason I implemented it like so, is because It will facilitate the implementation process afterward.
We think it will be a nice addition to integrate this feature to all vis and agg types in the system. but I guess it will be a gradual process.

2022-03-10 19:57 UTC, kgcreative commented
I think it would be worth documenting all of the different visualizations that can use bucket aggregations. I think one question for the community here is if we want to have to pass all the different visualization types in order to change the split limit on all of them, or if there is an approach that can cover all visualization types, and, if desired, control individual visualizations at a more granular level.

From reading the issue, this seems to come from a desire to limit potentially expensive queries on large data sets, so it feels like a single setting to control the split limit everywhere it's used would be friendlier than having to control these individually

2022-03-16 07:38 UTC, RoyiSitbon commented
> I think it would be worth documenting all of the different visualizations that can use bucket aggregations. I think one question for the community here is if we want to have to pass all the different visualization types in order to change the split limit on all of them, or if there is an approach that can cover all visualization types, and, if desired, control individual visualizations at a more granular level.
> 
> From reading the issue, this seems to come from a desire to limit potentially expensive queries on large data sets, so it feels like a single setting to control the split limit everywhere it's used would be friendlier than having to control these individually

Hey @kgcreative, thanks for replying.
I understand what you are saying, who would be able to answer this type of question?
How will we understand if this solution is legit, and can be merged as-is or required to accommodate?

Thanks

2022-06-03 09:23 UTC, ashwin-pc requested changes
Based on #1178 this does not seem to address the real problem here. If the goal is to limit expensive aggregations dynamically, this only does that for the table agg and that too for the `Split Row` agg type. I believe that issue needs a lil more discussion before we implement a solution. I'll call out my concerns and possible solutions in that issue.

2022-06-22 19:02 UTC, joshuarrrr commented
@RoyiSitbon I'm going to convert this to a draft until we can come to consensus on a more general approach as discussed in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1178.

2022-09-26 20:39 UTC, seanneumann commented
We are closing this PR because what it says and does is very different. Next steps to resolve the discussion on https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1178. After that feel free to open a new PR.

2022-09-26 20:39 UTC, closed without merging