change version in package.json
opensearch-project/OpenSearch-Dashboards pull request #2335
Opened 2022-09-12 23:15 UTC by BionIT

Signed-off-by: Lu Yu <nluyu@amazon.com>

### Description
change version in package.json
 
### Issues Resolved
NA 
### Check List
- [ x] New functionality includes testing.
  - [x ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x ] Commits are signed per the DCO using --signoff

2022-09-12 23:17 UTC, Flyingliuhub approved these changes

2022-09-12 23:26 UTC, noCharger approved these changes

2022-09-12 23:34 UTC, zhongnansu approved these changes

2022-09-12 23:41 UTC, ashwin-pc requested changes
Why are we going back in versions??

2022-09-13 00:10 UTC, seraphjiang commented
yes, we are backport to 1.x, and 2.x so any customer need it could be benefited

2022-09-13 01:43 UTC, ashwin-pc approved these changes
Discussed offline. This is an exception rather than the rule. The release process needs to be improved. Approving this change for now.

2022-09-13 01:43 UTC, merged