Update map client
opensearch-project/OpenSearch-Dashboards pull request #323
Opened 2021-04-29 20:19 UTC by kavilla

### Description
Update the map client to use: `https://maps.search-services.aws.a2z.com/`. Potentially further cleanup can be made but this makes map client work out of the box.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/221
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

2021-04-29 20:23 UTC, mihirsoni requested changes
Thanks @kavilla  for the changes, few minor comments.

2021-04-29 20:23 UTC, mihirsoni commented on src/plugins/maps_legacy/public/common/opensearch_maps_client.js
> +      kbn_version: kbnVersion,
This should `osd_version`

2021-04-29 20:23 UTC, mihirsoni commented on src/plugins/maps_legacy/public/common/opensearch_maps_client.js
> +      kbn_version: kbnVersion,
Similar `osdVersion`

2021-04-29 20:23 UTC, mihirsoni commented on src/plugins/maps_legacy/public/common/opensearch_maps_client.js
> +      kbn_version: kbnVersion,
Rename all kbn to `osd`

2021-04-29 21:36 UTC, kavilla commented on src/plugins/maps_legacy/public/common/opensearch_maps_client.js
> +      kbn_version: kbnVersion,
Good catch

2021-04-30 17:28 UTC, mihirsoni approved these changes
LGTM !! Thanks for the changes.

2021-04-30 17:36 UTC, seraphjiang approved these changes

2021-04-30 19:42 UTC, merged