Corrects NOTICE file copyright date range
opensearch-project/OpenSearch-Dashboards pull request #3308
Opened 2023-01-23 17:44 UTC by tmarkley

### Description
* Follow-up on #3051
 
### Issues Resolved
Resolves #765
 
### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-02-10 23:54 UTC, zhongnansu approved these changes

2023-02-10 23:58 UTC, AMoo-Miki requested changes

2023-02-10 23:58 UTC, AMoo-Miki commented on CHANGELOG.md
> +- Corrects NOTICE file copyright date range ([#3308](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3308))
```suggestion
- Correct NOTICE file's copyright date range ([#3308](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3308))
```

2023-02-11 07:45 UTC, zhongnansu approved these changes

2023-02-14 23:23 UTC, kristenTian approved these changes

2023-02-15 23:56 UTC, joshuarrrr commented
Overriding DCO failure from @zhongnansu changelog update - will be fixed in squash and merge.

2023-02-15 23:59 UTC, joshuarrrr commented
I suggest that the best way to backport this is to manually make a PR that combines this commit and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3051

2023-02-15 23:59 UTC, merged