Simplifies `re2` upgrade instructions
opensearch-project/OpenSearch-Dashboards pull request #3328
Opened 2023-01-25 23:58 UTC by tmarkley

### Description
* Follow-up from #3018 based on [Miki's suggestion](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3018#discussion_r1085708386).
 
### Issues Resolved
N/A
 
### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-02-09 08:38 UTC, AMoo-Miki requested changes

2023-02-09 08:38 UTC, AMoo-Miki commented on CHANGELOG.md
> +- Simplifies `re2` upgrade instructions ([#3328](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3328))
```suggestion
- Simplify the in-code instructions for upgrading `re2` ([#3328](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3328))
```

2023-03-07 22:11 UTC, abbyhu2000 commented on CHANGELOG.md
> +- Simplifies `re2` upgrade instructions ([#3328](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3328))
Changed recording to commit suggestion.

2023-03-07 22:12 UTC, abbyhu2000 approved these changes

2023-03-07 22:14 UTC, AMoo-Miki approved these changes

2023-03-07 23:36 UTC, merged