[Manual Backport 2.5][CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0
opensearch-project/OpenSearch-Dashboards pull request #3349
Opened 2023-01-27 04:59 UTC by ananzh

Backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345

Issue Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3329

 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-01-27 05:05 UTC, abbyhu2000 submitted a review, later dismissed

2023-01-27 05:05 UTC, AMoo-Miki approved these changes

2023-01-27 05:20 UTC, AMoo-Miki approved these changes

2023-01-27 05:20 UTC, abbyhu2000 submitted a review, later dismissed

2023-02-09 08:35 UTC, AMoo-Miki requested changes

2023-02-09 08:35 UTC, AMoo-Miki commented on CHANGELOG.md
> +- [CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0 ([#3345](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345))
```suggestion
- [CVE-2022-25860] Bump simple-git from `^3.15.0` to `^3.16.0` ([#3345](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345))
```

2023-02-10 18:15 UTC, AMoo-Miki submitted a review, later dismissed

2023-02-10 18:46 UTC, abbyhu2000 approved these changes

2023-02-24 23:04 UTC, AMoo-Miki approved these changes

2023-02-24 23:05 UTC, AMoo-Miki commented
Is this needed, now that 2.6.0 is on the way out?

2023-02-24 23:38 UTC, ananzh commented
2.5 is not an active branch since we cut 2.6

2023-02-24 23:38 UTC, closed without merging