Add default size for custom vector map
opensearch-project/OpenSearch-Dashboards pull request #3399
Opened 2023-02-08 20:58 UTC by VijayanB

### Description
With Custom Import Vector map, Region Maps loads only first 10 GeoJSON Features from previously imported Custom GeoJSON file( default size for OpenSearch ) . Hence, only top 10 Feature is available for joining index pattern in Region Maps and users might mistake, that only 10 features are available for join.

This solution will fetch up to 10K Features from OpenSearch. We  will also add this limit while uploading Custom Vector Map to keep it consistent with fetching and uploading as well. 

This limit is added after checking features count from default vector map service ( max is 255 ).

Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
 
### Issues Resolved
https://github.com/opensearch-project/dashboards-maps/issues/220
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-02-09 08:25 UTC, AMoo-Miki requested changes

2023-02-09 08:25 UTC, AMoo-Miki commented on src/plugins/region_map/common/constants/shared.ts
> +export const DEFAULT_INDEX_FETCH_SIZE = 10000; // opensearch index.max_result_window default value
Is there any reason why this is a fixed value and not configurable?

2023-02-09 08:25 UTC, AMoo-Miki commented on src/plugins/region_map/server/routes/opensearch.ts
> +import { DEFAULT_INDEX_FETCH_SIZE } from '../../common/constants/shared';
`../../common` should be exporting this and then the constant should be imported the other ones:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d9dc91de7e5c36625bb2ea01ba9453446f0307e9/src/plugins/region_map/public/components/map_choice_options.tsx#L24

2023-02-10 04:32 UTC, AMoo-Miki approved these changes
Thanks for doing all this.

2023-02-10 22:24 UTC, zhongnansu approved these changes
lgtm

2023-02-10 22:37 UTC, VijayanB commented
Thanks @AMoo-Miki @zhongnansu . Can you merge and back port to 2.x?

2023-02-13 17:16 UTC, merged

2023-02-13 21:32 UTC, kavilla commented
@VijayanB, just a heads up. With the current state of security multi-tenancy please be aware that configs get set in the system index `.kibana`. For multi-tenancy, the global tenant is `.kibana` but private tenants will have their own `.kibana_xyzuser`. Often end-users get confused why their UI settings do not get applied globally to all tenants so be prepared so often I suggest to circumvent this is to also add a YAML configuration.

2023-02-13 21:36 UTC, VijayanB commented
> @VijayanB, just a heads up. With the current state of security multi-tenancy please be aware that configs get set in the system index `.kibana`. For multi-tenancy, the global tenant is `.kibana` but private tenants will have their own `.kibana_xyzuser`. Often end-users get confused why their UI settings do not get applied globally to all tenants so be prepared so often I suggest to circumvent this is to also add a YAML configuration.

Thanks @kavilla , IUC, i have to add parameter and comment it inside config/opensearch-dashbaords.yml file as follow up pr?