[CVE-2023-25166] Bumps formula to 3.0.1
opensearch-project/OpenSearch-Dashboards pull request #3416
Opened 2023-02-10 18:30 UTC by zhongnansu

Signed-off-by: Su <szhongna@amazon.com>

### Description
[CVE-2023-25166] Bumps formula to 3.0.1
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-02-10 23:04 UTC, ananzh submitted a review, later dismissed
Nice!

2023-02-10 23:09 UTC, AMoo-Miki requested changes

2023-02-10 23:09 UTC, AMoo-Miki commented on CHANGELOG.md
> +- [CVE-2023-25166] Bumps formula to 3.0.1 ([#3416](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3416))
```suggestion
- [CVE-2023-25166] Bump formula to 3.0.1 ([#3416](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3416))
```

2023-02-10 23:35 UTC, ananzh approved these changes

2023-02-10 23:56 UTC, AMoo-Miki approved these changes

2023-02-11 00:06 UTC, abbyhu2000 approved these changes

2023-02-11 07:44 UTC, merged

2023-02-17 21:18 UTC, joshuarrrr commented
`formula` is not a dependency of `1.x`. No need to backport there.