Added untriaged issue workflow.
opensearch-project/OpenSearch-Dashboards pull request #3427
Opened 2023-02-14 17:51 UTC by dblock

Coming from https://github.com/opensearch-project/.github/issues/133, create a GitHub workflow for labelling untriaged issues. Please ensure that an untriaged label with color  exists before merging.

2023-02-15 19:39 UTC, kristenTian approved these changes

2023-02-16 01:51 UTC, joshuarrrr requested changes
We need to instead just rename the existing workflow we have: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/add_untriaged_label.yml

2023-02-16 01:56 UTC, joshuarrrr approved these changes

2023-02-16 08:33 UTC, kavilla approved these changes

2023-02-16 19:00 UTC, merged