Updates NOTICE file, adds validation to GitHub CI & Corrects NOTICE f…
opensearch-project/OpenSearch-Dashboards pull request #3453
Opened 2023-02-17 20:33 UTC by kristenTian

…ile copyright date range

* Aligns NOTICE with rules outlined in https://github.com/opensearch-project/.github/issues/21.
* Adds NOTICE validation to the build and test workflow.
* Fixes product name discrepancies between repository NOTICE file and the generated NOTICE file for the build.
* Skips template-izing the build and test workflow since that's being worked on in #2991.

Resolves #765

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-02-20 17:26 UTC, AMoo-Miki commented
Do we know that 1.x does not use any of those software removed from the NOTICE file?

2023-02-22 21:40 UTC, joshuarrrr requested changes
See also https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3452#pullrequestreview-1304375698 about date range start change

2023-03-10 20:57 UTC, ashwin-pc commented
@AMoo-Miki This PR also includes a workflow step to validate that the notice file is accurate and it passes that step. I also manually validated the ones that were removed and they dont exist in the repo.

2023-03-10 21:58 UTC, joshuarrrr approved these changes

2023-03-10 23:07 UTC, ashwin-pc approved these changes

2023-03-10 23:22 UTC, merged