Relax Node.js version to `^14.20.1` and bump `.nvmrc` to `v14.21.3`
opensearch-project/OpenSearch-Dashboards pull request #3463
Opened 2023-02-20 16:58 UTC by AMoo-Miki

### Description

* `engines.node` is relaxed from `14.20.1` to `^14.20.1`: yarn and OSD will allow version greater or equal to 14.20.1 to be used but do not impose upgrading to avoid being a breaking change. Users will be able to install any version of Node.js that satisfies `^14.20.1`, moving ahead without waiting for a change in OSD when new versions are released.
* `.nvmrc` is bumped to the latest security patch: `14.21.3`

 
### Check List
- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

2023-02-20 17:33 UTC, seanneumann submitted a review, later dismissed
👍

2023-02-20 17:37 UTC, abbyhu2000 approved these changes

2023-02-20 20:20 UTC, joshuarrrr approved these changes

2023-02-20 20:21 UTC, joshuarrrr requested changes
@AMoo-Miki There are some snapshots that need to be updated.

2023-02-21 03:41 UTC, joshuarrrr approved these changes

2023-02-21 16:16 UTC, abbyhu2000 approved these changes

2023-02-21 16:25 UTC, merged