Add 2.6 release note
opensearch-project/OpenSearch-Dashboards pull request #3484
Opened 2023-02-22 17:52 UTC by ananzh

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3447
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-02-22 21:05 UTC, joshuarrrr requested changes

2023-02-22 21:06 UTC, joshuarrrr requested changes

2023-02-22 21:06 UTC, joshuarrrr commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- [CVE-2023-25166] Bump formula from `3.0.0` to `3.0.1` ([#3416](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3416)
```suggestion
- [CVE-2023-25166] Bump formula from `3.0.0` to `3.0.1` ([#3416](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3416))
```

2023-02-22 23:20 UTC, ananzh commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- Make build scripts find and use the latest version of Node.js that satisfies `engines.node` ([#3467](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3467))
will move to maintenance

2023-02-22 23:22 UTC, ananzh commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- [Multiple DataSource] Refactor test connection to support SigV4 auth type ([#3456](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3456))
Will add it

2023-02-22 23:23 UTC, ananzh commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- Bump the version of Node.js installed by `nvm` to `14.21.3` ([3463](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3463))
will add

2023-02-22 23:25 UTC, ananzh commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- Relax the Node.js requirement to `14.20.1` ([3463](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3463))
Thanks. Then our changelog might also require a fix

2023-02-22 23:25 UTC, ananzh commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- [CVE-2020-36632] Bumps flat from `4.1.1` to `5.0.2` ([#3419](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3419))
will fix

2023-02-22 23:59 UTC, joshuarrrr commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- Relax the Node.js requirement to `14.20.1` ([3463](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3463))
Yeah, we'll need to audit/update the CHANGELOG in a separate PR anyway.

2023-02-23 00:03 UTC, joshuarrrr requested changes

2023-02-23 00:03 UTC, joshuarrrr commented on release-notes/opensearch-dashboards.release-notes-2.6.0.md
> +- Bump the version of Node.js installed by `nvm` to `14.21.3` ([#3463](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3463))
as per @AMoo-Miki we should remove these, as the backport didn't make it: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3486

```suggestion
```

2023-02-23 00:26 UTC, joshuarrrr approved these changes

2023-02-23 00:30 UTC, kavilla approved these changes

2023-02-23 00:35 UTC, merged