Omit adding the `osd-version` header when the Fetch request was explicitly asked to not prepend the `basePath`
opensearch-project/OpenSearch-Dashboards pull request #3643
Opened 2023-03-21 18:25 UTC by AMoo-Miki

### Description
Making `fetch` requests using `core/public/http/fetch`, an `osd-version` header is forcefully added, even to external requests. This change relies on the `prependBasePath` option passed to `fetch`, to guess if the request is external and to omit adding this header.
 
### Issues Resolved
Fixes #3277
 
### Check List
- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

2023-03-21 23:03 UTC, kavilla requested changes
I think the failures since we utilized this for XRSF.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/de0634495ebace79453b50421e8d147104a7b562/src/core/server/http/lifecycle_handlers.ts#L57 tries to find a header and then it can't find it so it throws the error.

It might not be the proper way of handling XSRF but by removing it causes these errors to be thrown.

2023-03-22 19:35 UTC, AMoo-Miki commented
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/de0634495ebace79453b50421e8d147104a7b562/src/core/server/http/lifecycle_handlers.ts#L57

If it is a `GET` or `OPTIONS` call, in will not fail and also if it contains the `osd-xsrf`. https://github.com/opensearch-project/OpenSearch-Dashboards/commit/621bf0efec3e96884b86d94462b1698171933f87 suggests `osd-version` used to be used for XSRF prior to K5 and they never cared to clean the code up over the next 6 years. I have added `osd-xsrf` to any call that was using `osd-version` for XSRF protection.

2023-03-23 01:12 UTC, joshuarrrr commented
@AMoo-Miki There are some snapshots that need updating.

2023-04-17 21:30 UTC, kavilla approved these changes
I think looks good to me. Pulled it down working. It's also working with the basic settings for security plugin.

One thing I'm not able to completely test is if any functionality relied on the `osd-version` header being present just so the redirect can be attached to the request and not fail.

For example, on `main`:
This succeeds:
```
curl localhost:5601/hdn/api/status -ku 'admin:admin'
```
This succeeds:
```
curl localhost:5601/hdn/api/status -ku 'admin:admin' -H osd-version:3.0.0
```
This succeeds:
```
curl localhost:5601/hdn/api/status -ku 'admin:admin' -H osd-version:
```
This fails:
```
curl localhost:5601/hdn/api/status -ku 'admin:admin' -H osd-version:3.5.0
```
Which makes sense because the version mismatch. So if any functionality outside of what I tested relied on the osd-version and utilized the fetch call might be broken if the fetch was passed from one request to another. 

So I don't know want to block it on something that I can't test especially if the value being not present still works for us. But I do believe we might want to mention in higher in the changelog.

Like something that mentions,

HTTP Fetch from Core OpenSearch Dashboards no longer default appends the `osd-version`.

2023-04-17 22:09 UTC, AMoo-Miki commented
Rocky, this change makes sure `osd-xsrf` is used all over and only removed `node-version` when the call is to a destination outside of OSD; any call to OSD will have `node-version`.

2023-04-17 22:22 UTC, joshuarrrr approved these changes
@AMoo-Miki Is there a follow-up issue already created to keep track of these todos?

2023-04-17 22:22 UTC, joshuarrrr commented on src/core/server/http/lifecycle_handlers.ts
> +    // ToDo: Remove !hasVersionHeader; `osd-version` incorrectly used for satisfying XSRF protection
nit - todo comments should have issues opened to link to.

2023-04-17 22:23 UTC, merged