[CCI][#3600][BUG] Fixed timestamp with zeros after decimal point
opensearch-project/OpenSearch-Dashboards pull request #3684
Opened 2023-03-24 00:19 UTC by frost017

### Description
Before Dashboard was showing timestamp something like this: Mar 13, 2023 @ 18:13:13.**678000000**. Now Dashboard shows timestamp exactly as in the source(Mar 13, 2023 @ 18:13:13.678**668399**). For example the source timestamp: 
```
PUT my-index-000001
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date"
      }
    }
  }
}

POST my-index-000001/_doc/
{
  "abc": "def",
  "timestamp": "2023-03-13T13:13:13.678668399Z"
}

GET my-index-000001/_search
```

**Result:**

<img width="571" alt="image" src="https://user-images.githubusercontent.com/71363024/227391316-15c39353-92b4-4a49-8a90-c73484ca62c3.png">

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3600

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-03-29 22:03 UTC, AMoo-Miki requested changes
I wonder if we should take this behavior to `src/plugins/data/common/index_patterns` so every other function using it can benefit.

2023-03-30 22:42 UTC, frost017 commented on CHANGELOG.md
> +- [Dashboard] Fixes timestamp with zeros after decimal point([#3684](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3684))
Hi! Thanks, changed it!

2023-03-30 22:45 UTC, frost017 commented
> I wonder if we should take this behavior to `src/plugins/data/common/index_patterns` so every other function using it can benefit.

Hi! 
Initially I also though about this, but as for me it seems to be a breaking change. I guess there are a lot places where methods from this file `src/plugins/data/common/index_patterns` are used. Also it may need thorough research to accomplish this safely.

2023-04-11 15:39 UTC, joshuarrrr commented
@frost017 I'd start by tracking down all the places that use the `indexPattern.formatHit(hit, 'html')` method. Anywhere that's used, the timestamp formatting may be wrong. As far as I remember, the `html` formatter is not used as commonly, and may have some other formatting bugs.

2023-04-25 19:22 UTC, joshuarrrr commented
@frost017 I'm marking this as a draft for now, until you have a chance to work on it some more.

2023-05-11 17:30 UTC, kavilla requested changes
Thank you @frost017 for this and I appreciate the work here. But I think the fix should be an indicator for the user. More information: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3600#issuecomment-1544401557

2023-05-23 12:28 UTC, frost017 commented
Hi! Thank you for suggestions! I am actively working on it

2023-05-25 16:16 UTC, kavilla commented
Closing as `valued effort` this contribution will not be merged but still be recognized as a "contribution". If you would like to open another PR that provides in app assistance with this please feel free to do so @frost017 !

Sorry about this and thanks again!

2023-05-25 16:16 UTC, closed without merging