Add edits to noDocumentation links
opensearch-project/OpenSearch-Dashboards pull request #3685
Opened 2023-03-24 11:05 UTC by sayuree

### Description
[Added corresponding links from the documentation for non-working links
 Edited DocLinksStart interface properties
 Edited the usage of interface in other files correspondigly
]
 
### Issues Resolved
[#3208]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-03-27 03:19 UTC, Abyl10 commented
Thank you for your recent code changes! I noticed that the ```CHANGELOG.md``` file was not updated to reflect the recent changes. It's important that we keep the changelog up-to-date so that other developers can understand what changes were made, why they were made, and how they may impact the codebase. Could you please update the ```CHANGELOG.md``` file with as much detail as possible?

2023-03-27 19:59 UTC, joshuarrrr requested changes
@sayuree Thanks for the PR - it mostly looks great!

I found some additional links that can be defined.

There are also some minor requested changes.

2023-03-28 09:15 UTC, sayuree commented on CHANGELOG.md
> +- [Tech Debt] Clean up docs_link_service organization so that strings are in the right categories. ([#3208](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3685))
Yes, I have updated the link to PR in a later commit

2023-03-29 16:10 UTC, joshuarrrr reviewed
@sayuree Can you also add the commented links to the `restAPI` section (L330-340)?

2023-03-29 17:08 UTC, joshuarrrr commented on src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx
> +          <EuiLink href={docLinks.links.opensearch.openSearchForum} target="_blank">
Please also update the mock in src/plugins/data_source_management/public/mocks.ts

2023-03-29 23:02 UTC, joshuarrrr commented on src/core/public/doc_links/doc_links_service.ts
> +          functionbeat: `${OPENSEARCH_WEBSITE_DOCS}`,
For each of these, let's use `${OPENSEARCH_WEBSITE_DOCS}tools/index/#downloads`

2023-04-04 01:49 UTC, joshuarrrr commented
@sayuree Will you be able to make the additional requested changes?

2023-04-04 17:27 UTC, sayuree commented
@joshuarrrr Added requested changes

2023-04-04 17:57 UTC, joshuarrrr reviewed
Thanks @sayuree , almost there! Just three tasks left, summarized here:

1. Can you also add the commented links to the restAPI section (L345-355)?
2. Please also update the mock in src/plugins/data_source_management/public/mocks.ts
3. See suggested changes for `visualize.guide` link.

2023-04-04 17:57 UTC, joshuarrrr commented on src/core/public/doc_links/doc_links_service.ts
> +            guide: `${OPENSEARCH_WEBSITE_DOCS}`,
```suggestion
            // https://opensearch.org/docs/latest/dashboards/visualize/viz-index/
            guide: `${OPENSEARCH_WEBSITE_DOCS}visualize/viz-index/`,
```

2023-04-05 16:45 UTC, joshuarrrr commented on src/plugins/data_source_management/public/mocks.ts
> +    opensearch: {
```suggestion
    noDocumentation: {
```

2023-04-11 15:40 UTC, joshuarrrr commented
@sayuree Can you rebase or update the PR to resolve the conflict? I believe the experimental callout has since been removed.

2023-04-11 19:12 UTC, sayuree commented
> @sayuree Can you rebase or update the PR to resolve the conflict? I believe the experimental callout has since been removed.

I have updated the PR, hope changes will be approved.

2023-04-13 00:22 UTC, joshuarrrr approved these changes

2023-04-13 02:15 UTC, AMoo-Miki approved these changes

2023-04-13 20:47 UTC, merged