[BUG][Console] Fix updating of play and wrench button
opensearch-project/OpenSearch-Dashboards pull request #3920
Opened 2023-04-21 22:46 UTC by kavilla

### Description

Fix UI bug that did not update the console with the correct values.

offsetTop was always 0 and the value needed the pixel.

### Issues Resolved
closes: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3916

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-04-21 22:58 UTC, kavilla commented
links failing from things not added.

2023-04-22 00:47 UTC, joshuarrrr commented
@kavilla Was this a regression from one of the recent changes to the console or a latent bug? If it's a regression, it would be nice to link the PR here for context. Also, if you have a little animation of the fixed behavior, that'd be 🥇 .

2023-04-22 00:50 UTC, joshuarrrr commented
ah, yeah, this is the PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3733

2023-04-22 00:51 UTC, kavilla commented
> @kavilla Was this a regression from one of the recent changes to the console or a latent bug? If it's a regression, it would be nice to link the PR here for context.

Yeah this one: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3733

Basically we previously got a number and jquery would automagically add the `px` if it was a number.

2023-04-22 00:56 UTC, joshuarrrr approved these changes
This looks good, but I don't think we need a release note - it's just a fix/continuation of the jquery removal PR already included.

2023-04-22 00:56 UTC, joshuarrrr commented on release-notes/opensearch-dashboards.release-notes-2.7.0.md
> +- [Console] Fix dev tool console not updating action bar ([#3920](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3920))
No need to update the release notes with this, since it was only introduced in the same release

```suggestion
```

2023-04-22 00:57 UTC, joshuarrrr commented on CHANGELOG.md
> +- [Console] Fix dev tool console not updating action bar ([#3920](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3920))
```suggestion
- [Console] Fix dev tool console not updating action bar relative position ([#3920](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3920))
```

2023-04-22 00:57 UTC, joshuarrrr approved these changes

2023-04-22 01:03 UTC, ananzh approved these changes

2023-04-24 16:19 UTC, joshuarrrr requested changes
This fix is not sufficient. Instead, we should revert https://github.com/opensearch-project/OpenSearch-Dashboards/commit/b7af56f86a359409c8681b22b950d4aadd8ae7fb, because autocompletion and documentation links are also broken with that commit.

2023-04-24 19:11 UTC, kavilla commented
Closing for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3929

2023-04-24 19:11 UTC, closed without merging