[BUG][Dashboard listing] push to history if dashboard otherwise nav
opensearch-project/OpenSearch-Dashboards pull request #3922
Opened 2023-04-22 03:36 UTC by kavilla

### Description

History push will just to the current route. However, dashboardsProvider was implemented with the expectation that it was a different app.

So when a plugin registered it was attempting to navigate to `app/dashboard#/app/{url}`

### Issues Resolved

n/a

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-04-24 15:48 UTC, dblock requested changes
This needs tests.

2023-04-24 20:35 UTC, dblock commented
Can we please fix the link checker?

```
Errors in scripts/jest.js
✗ https://facebook.github.io/jest/docs/cli.html (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/docs/cli.html))

Errors in packages/opensearch-eslint-config-opensearch-dashboards/README.md
✗ https://facebook.github.io/jest/ (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/))

Errors in scripts/jest_integration.js
+ echo
✗ https://facebook.github.io/jest/docs/cli.html (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/docs/cli.html))
```

2023-04-24 20:40 UTC, joshuarrrr commented
> ~Can we please fix the link checker?~
> 
> ```
> Errors in scripts/jest.js
> ✗ https://facebook.github.io/jest/docs/cli.html (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/docs/cli.html))
> 
> Errors in packages/opensearch-eslint-config-opensearch-dashboards/README.md
> ✗ https://facebook.github.io/jest/ (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/))
> 
> Errors in scripts/jest_integration.js
> + echo
> ✗ https://facebook.github.io/jest/docs/cli.html (HTTP status client error (404 Not Found) for url (https://facebook.github.io/jest/docs/cli.html))
> ```
> 
> #3931

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3931

2023-04-24 23:50 UTC, kavilla commented
working ci version: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/4790923834

2023-04-25 01:20 UTC, ashwin-pc approved these changes

2023-04-25 02:41 UTC, dblock approved these changes

2023-04-25 02:51 UTC, merged