This PR needs review Lodash->js
opensearch-project/OpenSearch-Dashboards pull request #3988
Opened 2023-05-06 11:39 UTC by Aigerim-ai

Please review this PR and let me know your thoughts on the following:

Is the location of the Lodash_to_js file okay?
Did I properly convert the necessary files?
Are there any potential issues with the package I installed?"

2023-05-16 16:33 UTC, abbyhu2000 commented
Hi @Aigerim-ai, could you update the PR title to be something descriptive? The PR title should summarize what this PR achieves in a clear way.

2023-06-02 23:00 UTC, ananzh requested changes
@Aigerim-ai First of all thank you for the PR. But I think this PR still requires some further modifications before it is ready for a full review.

2023-06-02 23:03 UTC, ananzh commented
@Aigerim-ai I would suggest for now revert the PR to a draft state and address some unexpected changes, like updating license, including un-used package, resolving something that is not related to the issue itself and add something unexpected. Then update PR title and CHANGELOG. Rebase it and make it a formal PR. If you need help, let us know.

2023-06-05 19:04 UTC, Aigerim-ai commented on package.json
> +    "resize-observer-polyfill": "1.5.1",
When I was installing dependency it showed me this issue, `npm ERR! code ETARGET
npm ERR! notarget No matching version found for resize-observer-polyfill@1.5.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@elastic/charts'
npm ERR! notarget `

2023-06-05 19:09 UTC, Aigerim-ai commented on src/plugins/opensearch_dashboards_utils/lodash_replacement/lodash_replacement.js
> +export function get(obj, path, defaultValue) {
The purpose of this file is to create reusable functions, such that when we will convert from lodash to javascript, we can easily import the functions

2023-06-05 19:09 UTC, Aigerim-ai commented on package.json
> +    "eslint-plugin-you-dont-need-lodash-underscore": "^6.12.0",
Yes, I got you! I am planning to push only changed files from lodash to javascript, the changes made in package.json will not appear in the future reviewed PRs, the plugin I have installed will only be needed to "detect" all lodash functions with in the project.

2024-07-25 16:19 UTC, ananzh commented
@Aigerim-ai Due to an extended period without updates, we're going to close this issue for now. We appreciate your contribution and understand that priorities and availability can change. Please feel free to reopen this issue when you have the opportunity to revisit it. Thank you for your understanding.

2024-07-25 16:19 UTC, closed without merging