[OSCI] [FIX] time conversion unit test bug
opensearch-project/OpenSearch-Dashboards pull request #5174
Opened 2023-10-02 22:36 UTC by thanhinhchtom

### Description

Fix Unit test bug with time conversion in point_series in chart

### Issues Resolved

fixes [#5165 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5165)

## Screenshot

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88635563/80ce441a-3f56-4048-98ee-5b049ac2b56d)

## Testing the changes

1. Run command `yarn test:jest src/plugins/discover/public/application/components/chart/utils/point_series.test.ts`

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-10-02 23:58 UTC, ashwin-pc requested changes
Nice! that was a quick fix. You seem to have added 2 files that are unrelated to the change though, can you remove those two?

Also can you add an entry to the Changelog for your fix?

2023-10-03 22:36 UTC, ananzh approved these changes

2023-10-04 02:36 UTC, AMoo-Miki approved these changes

2023-10-04 06:47 UTC, seanneumann approved these changes
👍

2023-10-04 17:59 UTC, ananzh approved these changes

2023-10-04 18:17 UTC, seanneumann approved these changes

2023-10-04 18:24 UTC, ashwin-pc approved these changes

2023-10-04 21:41 UTC, merged