[BUG] Resolve display issue and improve performance
opensearch-project/OpenSearch-Dashboards pull request #5514
Opened 2023-11-20 20:44 UTC by ananzh

### Description

### Issues Resolved

## Screenshot

## Testing the changes

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-01-29 23:46 UTC, ananzh commented
There are two functional tests broken by reload. If we think this could be a tmp fix, I could fix the tests as well.

2024-02-06 17:45 UTC, AMoo-Miki requested changes

2024-02-06 17:45 UTC, AMoo-Miki commented on CHANGELOG.md
> +- [BUG][Discover] Make table size adjustable according to table rows and columns ([#5514](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5514))
```suggestion
- [Discover] Make table size adjustable according to table rows and columns ([#5514](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5514))
```

2024-02-07 03:05 UTC, ananzh commented
close this since the issue is fixed

2024-02-07 03:05 UTC, closed without merging