[ignoreFilterIfFieldNotInIndex] Build separate Timeline filters by index
opensearch-project/OpenSearch-Dashboards pull request #6190
Opened 2024-03-19 01:17 UTC by neodescis

### Description

When ignoreFilterIfFieldNotInIndex is enabled:
1. Parse the Timeline visualization expression for indexes
2. For each index in the expression, build a separate OpenSearch query from the current filters
3. Pass the filters for each index to the Timeline request handler
4. In the request handler, use the index-specific query instead of the single index-agnostic query

### Issues Resolved

closes #6184

## Testing the changes

1. Enable ignoreFilterIfFieldNotInIndex 
2. Create dashboard with visualizations for more than one index
3. Create timeline visualization for one of those indexes and add it to the dashboard
4. Create filter that applies only to the index not referenced by the timeline visualization
5. The timeline visualization should no longer flatline, because the filter is no longer being applied to it

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

2024-04-18 14:30 UTC, ananzh commented
@neodescis Found an issue when I play with in. So in OSD, we can typically omit the explicit `index=` when specifying the index directly after the .es()/.os()/.opensearch() function. So the regex function `const indexRegEx = /index=['"]?([\sA-z0-9_\-\*]*?)[^\sA-z0-9_\-\*]/g;` will fail to capture the index.

For example, in the following expression, for opensearch_dashboards_sample_data_logs we have `index=` but for opensearch_dashboards_sample_data_ecommerce we omit
```
.es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).holt(0.8, 0.2, 0.8, 2h).color(#c6c6c6).lines(10).label('Prediction Value'), .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).color(red).lines(1).label('Actual Value'), .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).lines(1).holt(0.8, 0.2, 0.8, 2h).subtract(.es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes)).abs().if(lt, 500, null, .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes)).points(5,2,1.5).color(green).label('Anomaly Value').title('max types anomaly'),
.es(opensearch_dashboards_sample_data_ecommerce, metric=max:taxful_total_price).label('Maximum Price'),
.es(opensearch_dashboards_sample_data_ecommerce, metric=avg:taxful_total_price).movingaverage(window=7).label('7-day Avg Price Moving Average').color(green)

```

<img width="928" alt="Screenshot 2024-04-18 at 7 29 20 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/fa344fce-0831-46bf-92ea-5f11972b13fd">


If we add a filter to `opensearch_dashboards_sample_data_ecommerce`, then in your handler, because the regex function will only capture one index pattern 
<img width="603" alt="Screenshot 2024-04-18 at 7 12 27 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/b3098ef9-022c-4911-b0d3-8292e06e2895">

and this will cause the `filterByIndex` not apply the filter to the `opensearch_dashboards_sample_data_ecommerce`
<img width="482" alt="Screenshot 2024-04-18 at 7 10 44 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/9831970d-8e34-4d81-a679-e66c9e89a147">

2024-04-18 14:42 UTC, ananzh requested changes
@neodescis could you check my comment and fix the expression? Feel without `index=` is hard to capture. Maybe we could add `/\.(es|elasticsearch|os|opensearch)\(\s*['"]?([\w\-\*]+)['"]?/` since`.es, .elasticsearch, .os, .opensearch` can help to capture and index name is always the first one. But I am worried about potential edge cases, like could index name not be the first string in the expression or if there is any special characters in index names.

2024-04-18 19:18 UTC, neodescis commented
Thanks for looking at this, @ananzh. I appreciate the analysis. I didn't know that `index=` was optional. I understand the issue, and I will see what I can do.

2024-05-02 18:23 UTC, neodescis commented
> @neodescis Found an issue when I play with in. So in OSD, we can typically omit the explicit `index=` when specifying the index directly after the .es()/.os()/.opensearch() function. So the regex function `const indexRegEx = /index=['"]?([\sA-z0-9_\-\*]*?)[^\sA-z0-9_\-\*]/g;` will fail to capture the index.
> 
> For example, in the following expression, for opensearch_dashboards_sample_data_logs we have `index=` but for opensearch_dashboards_sample_data_ecommerce we omit
> 
> ```
> .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).holt(0.8, 0.2, 0.8, 2h).color(#c6c6c6).lines(10).label('Prediction Value'), .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).color(red).lines(1).label('Actual Value'), .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes).lines(1).holt(0.8, 0.2, 0.8, 2h).subtract(.es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes)).abs().if(lt, 500, null, .es(index=opensearch_dashboards_sample_data_logs,metric=max:bytes)).points(5,2,1.5).color(green).label('Anomaly Value').title('max types anomaly'),
> .es(opensearch_dashboards_sample_data_ecommerce, metric=max:taxful_total_price).label('Maximum Price'),
> .es(opensearch_dashboards_sample_data_ecommerce, metric=avg:taxful_total_price).movingaverage(window=7).label('7-day Avg Price Moving Average').color(green)
> ```
> 
> <img alt="Screenshot 2024-04-18 at 7 29 20 AM" width="928" src="https://private-user-images.githubusercontent.com/79961084/323645120-fa344fce-0831-46bf-92ea-5f11972b13fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjY0NjYsIm5iZiI6MTcxNDY2NjE2NiwicGF0aCI6Ii83OTk2MTA4NC8zMjM2NDUxMjAtZmEzNDRmY2UtMDgzMS00NmJmLTkyZWEtNWYxMTk3MmIxM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE2MDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOGQ4MjRmZWUwMGM2MDYzZWE3YTUxMjFhYzU1ZDU1YWMyZTNmMmQ1NzM4MjA3MmVhNGJhMTcxOWE1MDA5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YpGsM31dNYnyZj3VCSPbumO74OPfunjoas1UodyXw60">
> If we add a filter to `opensearch_dashboards_sample_data_ecommerce`, then in your handler, because the regex function will only capture one index pattern <img alt="Screenshot 2024-04-18 at 7 12 27 AM" width="603" src="https://private-user-images.githubusercontent.com/79961084/323643420-b3098ef9-022c-4911-b0d3-8292e06e2895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjY0NjYsIm5iZiI6MTcxNDY2NjE2NiwicGF0aCI6Ii83OTk2MTA4NC8zMjM2NDM0MjAtYjMwOThlZjktMDIyYy00OTExLWIwZDMtODI5MmUwNmUyODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE2MDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDI1MjJjYjQyZDY4ODU2ZjgxZDZhZGI4YzFkMmM2M2MyNzE2MmI3MTA2N2U4ODE1YTQwNzc0MzI2Y2E0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQilfgURuAiT-F_s7zFBbfa__Kck22n2R5YcRAYtId0">
> 
> and this will cause the `filterByIndex` not apply the filter to the `opensearch_dashboards_sample_data_ecommerce` <img alt="Screenshot 2024-04-18 at 7 10 44 AM" width="482" src="https://private-user-images.githubusercontent.com/79961084/323643356-9831970d-8e34-4d81-a679-e66c9e89a147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjY0NjYsIm5iZiI6MTcxNDY2NjE2NiwicGF0aCI6Ii83OTk2MTA4NC8zMjM2NDMzNTYtOTgzMTk3MGQtOGUzNC00ZDgxLWE2NzktZTY2YzllODlhMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE2MDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGViODRhMmU2MDhjZGI1NDVkMTQ3NWM1YjMzZDAzNTg1ZGFjMTQzOWE4MGYwZmNkY2Q0ZmZkNTJiMGY4NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qL-xCGhYCUevSeI4yDtojU3-I50I_C7UjMYGQvZm2Vw">

I've done some digging, and I've determined that the `.os()` function does not function as you stated. When omitting an argument's name, it seems the argument must be at a particular place in the list of arguments. In the case of the index argument, it must be supplied as the 4th argument to `.os()`. The first argument is for "query". I have verified this is how it works, as I get completely different results when using `.os(indexname)` and `.os(index=indexname)`. Furthermore, I found that it is [documented in Kibana](https://www.elastic.co/guide/en/kibana/current/timelion.html#_function_parameters), though I cannot find the same in the documentation for OpenSearch Dashboards.

That said, I do have a solution that supports the unnamed argument as the 4th parameter. I did end up changing the logic a fair amount to do so. I will get it pushed to this pull request soon.

2024-09-12 16:43 UTC, neodescis commented
Any chance anyone can look at this? @ananzh ?

2026-05-08 15:11 UTC, angle943 commented
This is Kiro posting.

This has been awaiting requested changes for 18+ months with no author activity. Recommend closing; please reopen or open a fresh PR if you'd like to continue the work.

2026-05-08 15:20 UTC, neodescis commented
I'm afraid that is false. Changes were made after the initial review, but never re-reviewed. We've given up on this getting merged long ago, however!

If you want to close the PR, feel free.

2026-05-08 20:58 UTC, closed without merging