Close any open flyouts when changing view mode of the dashboard
opensearch-project/OpenSearch-Dashboards pull request #6923
Opened 2024-06-05 17:15 UTC by AMoo-Miki

### Description

Adds a mechanism to close an active "service" flyout and employs that in the Dashboard editing flow.

## Changelog
- skip

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

2024-06-06 17:44 UTC, ananzh approved these changes

2024-06-06 18:30 UTC, ashwin-pc requested changes
Holding off accidentally merging it without a test

2024-06-28 21:07 UTC, ashwin-pc approved these changes
LGTM! Thanks for adding the tests :) 

Nit: Lets add a readme here for these overlay's and other core API's so that they show up in the developer docs

2024-07-01 17:21 UTC, abbyhu2000 approved these changes

2024-07-01 17:31 UTC, merged