[Discover] Remaining changes and fixes for discover and autosuggest
opensearch-project/OpenSearch-Dashboards pull request #7414
Opened 2024-07-23 21:29 UTC by mengweieric

### Description

- removed unused UI files causing issue
- remove unused antlr autogenerated files

### Issues Resolved

## Screenshot

## Testing the changes

## Changelog

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-07-25 01:04 UTC, ananzh approved these changes

2024-07-25 01:10 UTC, LDrago27 approved these changes

2024-07-25 01:13 UTC, sejli approved these changes

2024-07-25 01:14 UTC, ananzh commented
Hold to merge this PR since many tests failed

2024-07-25 01:14 UTC, ananzh requested changes
Hold to merge since many tests failed

2024-07-27 19:57 UTC, mengweieric commented
closing this as it was already included in latest main

2024-07-27 19:57 UTC, closed without merging