[Workspace] Fix issues in workspace detail and association modal
opensearch-project/OpenSearch-Dashboards pull request #8201
Opened 2024-09-14 10:48 UTC by Kapian1234

### Description
Fix issues in workspace detail and association modal

### Issues Resolved

## Screenshot

## Testing the changes

## Changelog

- fix: Fix issues in workspace detail and association modal

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-09-18 06:18 UTC, ruanyl commented
@Kapian1234 Is this PR ready for review?

2024-09-20 08:22 UTC, Kapian1234 commented on src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.scss
> +li[parentid] {
no, it just adds indentation to DQCs in association modal

2024-09-29 08:27 UTC, ruanyl commented on src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.scss
> +li[parentid] {
It is right? It applies to all `li` element with `parentid` attribute, but you only need to applies the style to the DQC  association modal if I understand correctly

2024-09-29 08:29 UTC, ruanyl requested changes
@wanglam Could you take a look at the comment and confirm?

2024-09-29 08:35 UTC, wanglam commented on src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.scss
> +li[parentid] {
Can we increase the div width in prepend element in [this line](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx#L119)?  Then we don't need add this customized css.

2024-09-29 09:07 UTC, Kapian1234 commented on src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.scss
> +li[parentid] {
Oh, I didn't consider that before. Add a div as prepend would be a better approach.

2024-10-29 09:15 UTC, closed without merging