Add a MetricsRecorder plugin for metrics reporting
opensearch-project/OpenSearch-Dashboards pull request #8628
Opened 2024-10-17 10:11 UTC by chishui

### Description
Add a MetricsRecorder plugin for metrics reporting.

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8625

## Screenshot

## Testing the changes

## Changelog

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2024-10-17 10:48 UTC, Hailong-am commented
Can we use telemetry plugin?

2024-10-18 01:56 UTC, ashwin-pc requested changes
Lets not rush a new reporting plugin without due consideration given to the original one. I dont agree with some of the assumptions made in the original issue. I'll call out my concerns there. Lets have a discussion on the original issue before proceeding with this change in core. lets discuss the drawbacks with the useage collection plugin and why we cant find workarounds before adding a new one here.

2024-10-18 01:58 UTC, chishui commented
> Can we use telemetry plugin?

telemetry plugin is built on top of usage_collection and it only collects metrics scattered in different places, it doesn't have mechanism to store metrics.

2024-10-28 03:08 UTC, chishui commented
@seraphjiang @zengyan-amazon could you take a look?

2026-05-08 15:12 UTC, angle943 commented
This is Kiro posting.

POC has `CHANGES_REQUESTED`. @chishui — is this POC still being actively pursued, or should it be closed in favor of a productionized design?

2026-05-09 00:01 UTC, closed without merging