TESTID-140: sidebar spec
opensearch-project/OpenSearch-Dashboards pull request #9128
Opened 2024-12-26 18:29 UTC by silvaf-dev

### Description

Implements all four test suites required by https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8946

### Issues Resolved

## Screenshot

## Testing the changes

## Changelog
- skip

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2024-12-27 23:19 UTC, angle943 commented
Could you rebase so that the diff only show your changes?

2024-12-30 16:59 UTC, silvaf-dev commented
> Could you rebase so that the diff only show your changes?

Done, but it'll still contain more changes than the ones I authored. The reason is I had to pull from Argus' PR in order to recover my lost refactors.
The files I modified were:
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
- src/plugins/data_explorer/public/components/sidebar/index.tsx (added data-test-subj)
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/helpers.js (added my functions below verifyDocTableFirstExpandedFieldFirstRowExistsFilterButtonFiltersCorrectField())

2024-12-31 22:45 UTC, angle943 requested changes

2024-12-31 22:45 UTC, angle943 commented on cypress.config.ts
> +  retries: 1,
This will affect every test config. Do we want to add this? I think someone with more experience in the codebase should comment

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/helpers.js
> + * @param del true/false. true: Deletes character to the right of the cursor; false: Deletes character to the left of the cursor
- I think this comment is outdated. This function only has `query` as argument, which is not listed as a param here
- Just FYI, i update the `setSingleLineQueryEditor` to be both used for both singleLine and multiLine here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9112/files#diff-c71a49edcd56336affaeb1dfd1e47f29965ee58b7b9368943ea1468bb9fb307aR6 . I believe you should be able to leverage that if my PR gets merged

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/helpers.js
> +}
This functionality already exists via `cy.setQueryLanguage()`. Can you try using that one and remove this one if it works?

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/helpers.js
> +export function checkSidebarFilterBarResults(search, assertion) {
For this and other functions (as well as callback functions), please see: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9119#discussion_r1898721855

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +const miscUtils = new MiscUtils(cy);
I don't remember the exact reasoning, but we haven't been using this. Instead we were using cy custom commands directly. I'll comment below where relevant

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  }
(no action needed). but just fyi, line 43-49 can be replaced by a custom command i am adding in my PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9112/files#diff-c71a49edcd56336affaeb1dfd1e47f29965ee58b7b9368943ea1468bb9fb307aR176 (minus the `setTopNavDate()`)

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +const addFields = (testFields, expectedValues, pplQuery, sqlQuery, indexPattern = true) => {
this functions looks to be doing much more than `addFields`. Could we possibly rename the function or perhaps break apart the function into more segregated functionalities?

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  const filterFields = () => {
This function seem to not be `filter(ing)Fields`, but rather verifying that the Sidebar filter bar data is correct. Could we update the name?

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +const checkFilteredFields = (indexPattern = true) => {
nitpick: `verifyFilteredFieldsForAllLanguages`

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +const checkCollapseAndExpand = (indexPattern = true) => {
nitpick: `checkSidebarPanelCollapseAndExpandBehavior = (isIndexPattern)` (i personally wouldn't provide a defaultValue for the argument for this)

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  const collapseAndExpand = (sql = false) => {
nitpick, there should be some mention of `sideParPanel` in the name of this, and `sql` should be `isSql`

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +const checkCollapse = (indexPattern = true) => {
nit: same line of comments as above

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +    miscUtils.visitPage('/app/home');
```suggestion
    cy.visit('/app/home');
```

2024-12-31 22:45 UTC, angle943 commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +    cy.navigateToWorkSpaceHomePage(`${BASE_PATH}`, `${WORKSPACE_NAME}`);
```suggestion
    cy.navigateToWorkspaceSpecificPage({
        url: BASE_PATH, 
        workspaceName: WORKSPACE_NAME,
        page: 'discover',
        isEnhancement: true,
    });
```

Reasoning is that the `homepage` in neo is not the discover page

2025-01-02 16:57 UTC, silvaf-dev commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +    cy.navigateToWorkSpaceHomePage(`${BASE_PATH}`, `${WORKSPACE_NAME}`);
Doesn't work for me. It gets stuck on this screen:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e0cfe5af-da67-4485-ab0e-cf43887aad4c" />

2025-01-02 19:02 UTC, silvaf-dev commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +    cy.navigateToWorkSpaceHomePage(`${BASE_PATH}`, `${WORKSPACE_NAME}`);
Fixed

2025-01-07 06:06 UTC, ananzh commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  const getDocTableHeaderByIndex = (index) => {
This function is doing too many things and has multiple nested helper functions. Consider:

* Breaking it into smaller, focused functions
* Using cy.wrap().each() for sequential operations
* Separating test setup from assertions
* Adding explicit language handling for different query types

This would improve test stability and make the code more maintainable. Here is a suggested version 
```
const addSidebarFieldsAndCheckDocTableColumns = (
  testFields,
  expectedValues,
  pplQuery,
  sqlQuery,
  isIndexPattern = true
) => {
  // Helper functions
  const getDocTableHeaderByIndex = (index) => 
    cy.getElementByTestId('docTableHeaderField').eq(index);

  const checkTableHeaders = (headers) => {
    headers.forEach((header, index) => {
      getDocTableHeaderByIndex(index + 1).should('have.text', header);
    });
  };

  const checkDocTableColumn = (values, columnNumber) => {
    values.forEach((value, index) => {
      dataExplorer.getDocTableField(columnNumber, index).should('have.text', value);
    });
  };

  const toggleFields = (fields) => {
    fields.forEach(field => {
      cy.getElementByTestId(`fieldToggle-${field}`).click();
    });
  };

  // Languages to test based on index type
  const languages = isIndexPattern ? 
    ['DQL', 'Lucene', 'PPL', 'OpenSearch SQL'] :
    ['PPL', 'OpenSearch SQL'];

  // Initial setup
  if (isIndexPattern) {
    dataExplorer.selectIndexPatternDataset(INDEX_PATTERN_NAME, 'DQL');
    cy.setQueryLanguage('DQL');
    cy.setTopNavDate(START_TIME, END_TIME);
  } else {
    dataExplorer.selectIndexDataset(DATASOURCE_NAME, INDEX_NAME, 'OpenSearch SQL', 'timestamp');
  }

 // Test field toggling and header persistence
 cy.wrap([
  // Check initial state
  () => getDocTableHeaderByIndex(1).should('have.text', '_source'),
  
  // Add fields and verify
  () => {
    toggleFields(testFields);
    getDocTableHeaderByIndex(1).should('not.have.text', '_source');
    checkTableHeaders(testFields);
  },

  // Test language persistence
  ...languages.map(language => () => {
    cy.setQueryLanguage(language);
    if (language !== 'OpenSearch SQL') {
      cy.setTopNavDate(START_TIME, END_TIME);
    }
    checkTableHeaders(testFields);
  }),

  // Test field removal
  () => {
    // Remove first two fields
    toggleFields(testFields.slice(0, 2));
    getDocTableHeaderByIndex(1).should('not.have.text', testFields[0]);
    getDocTableHeaderByIndex(2).should('not.have.text', testFields[1]);

    // Remove remaining fields
    toggleFields(testFields.slice(2));
    getDocTableHeaderByIndex(1).should('have.text', '_source');
    getDocTableHeaderByIndex(2).should('not.exist');

    // Add all fields back
    toggleFields(testFields);
    getDocTableHeaderByIndex(1).should('not.have.text', '_source');
    checkTableHeaders(testFields);
  }
  ]).each(fn => fn());

  // Check default hits only for index pattern before running queries
  if (isIndexPattern) {
    cy.setQueryLanguage('DQL'); // Ensure we're in DQL mode for hit check
    cy.getElementByTestId('discoverQueryHits').should('have.text', '10,000');
  }

  // Test queries
  cy.wrap([
    // PPL query
    () => {
      cy.setQueryLanguage('PPL');
      cy.intercept('**/api/enhancements/search/ppl').as('pplQuery');
      dataExplorer.sendQueryOnMultilineEditor(pplQuery);
      
      cy.wait('@pplQuery').then(() => {
        cy.wait(1000);
        checkTableHeaders(testFields);
        // Only check hits for index pattern with PPL query
        if (isIndexPattern) {
          cy.getElementByTestId('discoverQueryHits').should('have.text', '1,152');
        }
        checkDocTableColumn(expectedValues, 2);
      });
    },

    // SQL query
    () => {
      cy.setQueryLanguage('OpenSearch SQL');
      cy.intercept('**/api/enhancements/search/sql').as('sqlQuery');
      dataExplorer.sendQueryOnMultilineEditor(sqlQuery);
      
      cy.wait('@sqlQuery').then(() => {
        cy.wait(1000);
        checkTableHeaders(testFields);
        // No hits check for SQL query
        checkDocTableColumn(expectedValues, 2);
      });
    }
  ]).each(fn => fn());

  // Cleanup
  toggleFields(testFields);
};
```
It defines smaller helper function definitions at the top, like etDocTableHeaderByIndex, checkTableHeaders, checkDocTableColumn and etc. We should also consider to put them into utility functions if other tests use them in the future.

2025-01-07 06:07 UTC, ananzh commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  const checkSidebarFilterSearchResults = () => {
Same suggestion to refactor and make a better structure for this one. Here is a suggested one

```
const checkFilteredFieldsForAllLanguages = (isIndexPattern = true) => {
  const searchValues = [
    { search: '_index', assertion: 'equal' },
    { search: ' ', assertion: null },
    { search: 'a', assertion: 'include' },
    { search: 'age', assertion: 'include' },
    { search: 'non-existent field', assertion: null }
  ];

  // Set initial state
  if (isIndexPattern) {
    dataExplorer.selectIndexPatternDataset(INDEX_PATTERN_NAME, 'DQL');
    cy.setQueryLanguage('DQL');
    cy.setTopNavDate(START_TIME, END_TIME);
  } else {
    dataExplorer.selectIndexDataset(DATASOURCE_NAME, INDEX_NAME, 'PPL', 'timestamp');
  }

  // Test each query language
  ['DQL', 'Lucene', 'PPL', 'OpenSearch SQL'].forEach(language => {
    if ((!isIndexPattern && language === 'DQL') || (!isIndexPattern && language === 'Lucene')) {
      return;
    }
    
    cy.setQueryLanguage(language);
    searchValues.forEach(({ search, assertion }) => {
      dataExplorer.checkSidebarFilterBarResults(search, assertion);
    });
  });
};
```

2025-01-07 06:08 UTC, ananzh commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  const collapseAndExpand = (isSql = false) => {
Same here.

2025-01-07 06:08 UTC, ananzh commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +  if (isIndexPattern) {
Same here.

2025-01-07 06:12 UTC, ananzh commented on cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/sidebar_filtering.spec.js
> +      const pplQuery = 'source = data_logs_small_time_1 | where status_code = 200';
consider put these constants at the beginning of the describe, something like

```
describe('add fields', () => {
      const pplQuery = 'source = data_logs_small_time_1 | where status_code = 200';
      const sqlQuery = 'SELECT * FROM data_logs_small_time_1 WHERE status_code = 200';
      const testFields = ['service_endpoint', 'response_time', 'bytes_transferred', 'request_url'];
      const expectedTimeValues = ['3.32', '2.8', '3.35', '1.68', '4.98'];
      const nestedTestFields = [
        'personal.name',
        'personal.age',
        'personal.birthdate',
        'personal.address.country',
      ];
      const expectedAgeValues = ['28', '55', '76', '56', '36'];
      it('add field in index pattern', () => {...}
      ...
      // other tests
});
```

2025-01-07 22:08 UTC, ananzh commented
@silvaf-dev from https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/12658896186/job/35276829002?pr=9128, it seems that this cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/utils/sidebar_filtering.js is missing license header and there are some lint issues. Could you add a license header and also run `yarn lint --fix` to fix?

2025-01-28 01:03 UTC, ananzh commented
Close it as it is refactored by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9154

2025-01-28 01:03 UTC, closed without merging